apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-xcom-pvc
  namespace: spark-jobs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100m  # Define the storage size required
  storageClassName: standard  # Use the default storage class, you can customize if needed
