apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: job1-spark-job
  namespace: spark-jobs
spec:
  type: Python
  mode: cluster
  pythonVersion: "3"
  image: "test:latest"  # Replace with your custom image containing job1.py and job2.py
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/app/job1.py"  # Path to job1.py inside the container
  sparkVersion: "3.1.1"  # Use the appropriate Spark version
  restartPolicy:
    type: Never
  volumes:
    - name: "spark-jobs-volume"
      persistentVolumeClaim:
        claimName: "spark-xcom-pvc"  # Reference to your PVC with the correct name
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    volumeMounts:
      - name: "spark-jobs-volume"
        mountPath: "/opt/airflow/xcom"  # Mount PVC to /opt/airflow/xcom
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "spark-jobs-volume"
        mountPath: "/opt/airflow/xcom"  # Mount PVC to the same path for both driver and executor
---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: job2-spark-job
  namespace: spark-jobs
spec:
  type: Python
  mode: cluster
  pythonVersion: "3"
  image: "test:latest"  # Replace with your custom image containing job1.py and job2.py
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/app/job2.py"  # Path to job2.py inside the container
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  volumes:
    - name: "spark-jobs-volume"
      persistentVolumeClaim:
        claimName: "spark-xcom-pvc"  # Reference to your PVC with the correct name
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    volumeMounts:
      - name: "spark-jobs-volume"
        mountPath: "/opt/airflow/xcom"  # Mount PVC to /opt/airflow/xcom
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "spark-jobs-volume"
        mountPath: "/opt/airflow/xcom"  # Mount PVC to the same path for both driver and executor
